CREATE TABLE ALUMNOS
(ID INT(11)PRIMARY KEY AUTO_INCREMENT,
 CODIGO VARCHAR(8),
 NOMBRE VARCHAR(50),
 APELLIDOS VARCHAR(100),
 PROGRAMA VARCHAR(50));

 CREATE TABLE PROGRAMAS
 (PROGRAMA VARCHAR(50));

CREATE TABLE LABORATORIO
(COD_LABORATORIO VARCHAR(10) PRIMARY KEY,
NOMBRE_LABORATORIO VARCHAR(50));

CREATE TABLE PROFESOR
(COD_PROFESOR VARCHAR(10) PRIMARY KEY,
NOMBRE_PROFESOR VARCHAR(50),
APELLIDO_P_PROFESOR VARCHAR(50),
APELLIDO_M_PROFESOR VARCHAR(50));

CREATE TABLE CURSO
(COD_CURSO VARCHAR(10) PRIMARY KEY,
NOMBRE_CURSO VARCHAR(100));

CREATE TABLE LUNES
(COD_LUNES VARCHAR(10) PRIMARY KEY,
COD_CURSO VARCHAR(10),
NOMBRE_ASIGNATURA VARCHAR(100),
COD_PROFESOR VARCHAR(10),
FOREIGN KEY (COD_CURSO) REFERENCES CURSO (COD_CURSO),
FOREIGN KEY (COD_PROFESOR) REFERENCES PROFESOR (COD_PROFESOR));

CREATE TABLE MARTES
(COD_MARTES VARCHAR(10) PRIMARY KEY,
COD_CURSO VARCHAR(10),
NOMBRE_ASIGNATURA VARCHAR(100),
COD_PROFESOR VARCHAR(10),
FOREIGN KEY (COD_CURSO) REFERENCES CURSO (COD_CURSO),
FOREIGN KEY (COD_PROFESOR) REFERENCES PROFESOR (COD_PROFESOR));

CREATE TABLE MIERCOLES
(COD_MIERCOLES VARCHAR(10) PRIMARY KEY,
COD_CURSO VARCHAR(10),
NOMBRE_ASIGNATURA VARCHAR(100),
COD_PROFESOR VARCHAR(10),
FOREIGN KEY (COD_CURSO) REFERENCES CURSO (COD_CURSO),
FOREIGN KEY (COD_PROFESOR) REFERENCES PROFESOR (COD_PROFESOR));

CREATE TABLE JUEVES
(COD_JUEVES VARCHAR(10) PRIMARY KEY,
COD_CURSO VARCHAR(10),
NOMBRE_ASIGNATURA VARCHAR(100),
COD_PROFESOR VARCHAR(10),
FOREIGN KEY (COD_CURSO) REFERENCES CURSO (COD_CURSO),
FOREIGN KEY (COD_PROFESOR) REFERENCES PROFESOR (COD_PROFESOR));

CREATE TABLE VIERNES
(COD_VIERNES VARCHAR(10) PRIMARY KEY,
COD_CURSO VARCHAR(10),
NOMBRE_ASIGNATURA VARCHAR(100),
COD_PROFESOR VARCHAR(10),
FOREIGN KEY (COD_CURSO) REFERENCES CURSO (COD_CURSO),
FOREIGN KEY (COD_PROFESOR) REFERENCES PROFESOR (COD_PROFESOR));

 CREATE TABLE CURSOS
 (ID_ALUMNO VARCHAR(8),
 HORA VARCHAR(20),
 DIA VARCHAR(50),
 CURSO_DESCRIPCION VARCHAR(100),
 PROFESOR_DESCRIPCION VARCHAR(50),
 DESCRIPCION_LABORATORIO VARCHAR(20));
 
 CREATE TABLE HORARIO
 (PROGRAMA VARCHAR(50),
  MODULO VARCHAR(50),
  INICIO VARCHAR(10),
  FIN VARCHAR(10),
  COD_LUNES VARCHAR(10),
  COD_MARTES VARCHAR(10),
  COD_MIERCOLES VARCHAR(10),
  COD_JUEVES VARCHAR(10),
  COD_VIERNES VARCHAR(10),
  FOREIGN KEY (COD_LUNES) REFERENCES LUNES (COD_LUNES),
  FOREIGN KEY (COD_MARTES) REFERENCES MARTES (COD_MARTES),
  FOREIGN KEY (COD_MIERCOLES) REFERENCES MIERCOLES (COD_MIERCOLES),
  FOREIGN KEY (COD_JUEVES) REFERENCES JUEVES (COD_JUEVES),
  FOREIGN KEY (COD_VIERNES) REFERENCES VIERNES (COD_VIERNES));

 INSERT INTO LABORATORIO VALUES('LAB1','LAB 1');
 INSERT INTO LABORATORIO VALUES('LAB2','LAB 2');
 INSERT INTO LABORATORIO VALUES('LAB3','LAB 3');
 INSERT INTO LABORATORIO VALUES('LAB4','LAB 4');
 INSERT INTO LABORATORIO VALUES('LAB5','LAB 5');

 INSERT INTO PROFESOR VALUES('JMC','JORGE LUIS','MAYTA','CONDORI');
 INSERT INTO PROFESOR VALUES('RMC','RICHARD','MIRANDA','CACERES');
 INSERT INTO PROFESOR VALUES('GEV','GIANCARLO','ESCOBEDO','VALDIVIA');

 INSERT INTO CURSO VALUES('LPII','LENGUAJE PROGRAMACION II');
 INSERT INTO CURSO VALUES('DEPW','DESARROLLO E IMPLEMENTACION DE APLICACIONES WEB');
 INSERT INTO CURSO VALUES('ADSA','ANALISIS DE DISEÑO SISTEMAS AVANZADOS');
 INSERT INTO CURSO VALUES('POO','PROGRAMACION ORIENTADA A OBJETOS');

 INSERT INTO LUNES VALUES('LUN01','LPII','LENGUAJE DE PROGRAMACION II','JMC');
 INSERT INTO LUNES VALUES('LUN02','DEPW','DESARROLLO E IMPLEMENTACION DE APLICACIONES WEB','RMC');

 INSERT INTO MARTES VALUES('MAR01','ADSA','ANALISIS DE DISEÑO SISTEMAS AVANZADOS','GEV');
 INSERT INTO MARTES VALUES('MAR02','LPII','LENGUAJE DE PROGRAMACION II','JMC');

 INSERT INTO MIERCOLES VALUES('MIE01','ADSA','ANALISIS DE DISEÑO SISTEMAS AVANZADOS','GEV');
 INSERT INTO MIERCOLES VALUES('MIE02','DEPW','DESARROLLO E IMPLEMENTACION DE APLICACIONES WEB','RMC');
 
 INSERT INTO JUEVES VALUES('JUE01','LPII','LENGUAJE DE PROGRAMACION II','JMC');
 INSERT INTO JUEVES VALUES('JUE02','DEPW','DESARROLLO E IMPLEMENTACION DE APLICACIONES WEB','RMC');

 INSERT INTO VIERNES VALUES('VIE01','ADSA','ANALISIS DE DISEÑO SISTEMAS AVANZADOS','GEV');
 INSERT INTO VIERNES VALUES('VIE02','LPII','LENGUAJE DE PROGRAMACION II','JMC');
 

 INSERT INTO HORARIO VALUES('CASI IV','MOD II-T','2:00','2:45','LUN01','MAR01','MIE01','JUE01','VIE01');
 INSERT INTO HORARIO VALUES('CASI IV','MOD II-T','2:45','3:30','LUN01','MAR01','MIE01','JUE01','VIE01');
 INSERT INTO HORARIO VALUES('CASI IV','MOD II-T','4:00','4:45','LUN02','MAR02','MIE02','JUE02','VIE02');
 INSERT INTO HORARIO VALUES('CASI IV','MOD II-T','4:45','5:30','LUN02','MAR02','MIE02','JUE02','VIE02');


 INSERT INTO HORARIO VALUES('RECREO','RECREO','RECREO','RECREO','RECREO','RECREO','RECREO');
 INSERT INTO HORARIO VALUES('4:00','4:45','DEPW','LPII','DEPW','DEPW','LPII');
 INSERT INTO HORARIO VALUES('4:45','5:30','DEPW','LPII','DEPW','DEPW','LPII');


 SELECT 
 HORARIO.INICIO,
 LUNES.COD_CURSO,
 LUNES.COD_PROFESOR
 CURSO.NOMBRE_CURSO
 FROM HORARIO
 INNER JOIN LUNES ON HORARIO.COD_LUNES = LUNES.COD_LUNES;
 INNER JOIN CURSO ON CURSO.COD_LUNES = LUNES.COD_LUNES;

 SELECT 
 HORARIO.INICIO,
 HORARIO.FIN,
 LUNES.NOMBRE_ASIGNATURA AS LUNES_ASIGNATURA,
 PROFESOR.NOMBRE_PROFESOR,
 MARTES.NOMBRE_ASIGNATURA AS MARTES_ASIGNATURA,
 MIERCOLES.NOMBRE_ASIGNATURA AS MIERCOLES_ASIGNATURA,
 JUEVES.NOMBRE_ASIGNATURA AS JUEVES_ASIGNATURA,
 VIERNES.NOMBRE_ASIGNATURA AS VIERNES_ASIGNATURA
 FROM HORARIO
 LEFT JOIN LUNES ON LUNES.COD_LUNES = HORARIO.COD_LUNES
 LEFT JOIN PROFESOR ON PROFESOR.COD_PROFESOR = LUNES.COD_PROFESOR
 LEFT JOIN MARTES ON MARTES.COD_MARTES = HORARIO.COD_MARTES
 LEFT JOIN MIERCOLES ON MIERCOLES.COD_MIERCOLES = HORARIO.COD_MIERCOLES
 LEFT JOIN JUEVES ON JUEVES.COD_JUEVES = HORARIO.COD_JUEVES
 LEFT JOIN VIERNES ON VIERNES.COD_VIERNES = HORARIO.COD_VIERNES
 WHERE PROGRAMA='CASI IV' AND
 MODULO ='MOD II-T';

ella no te ama


 INSERT INTO CURSOS VALUES('73451138','2:00 2:45','LUNES','LEN. PROGRAMACION II','J.MAYTA','LAB 1');
 INSERT INTO CURSOS VALUES('73451138','2:45 3:30','LUNES','LEN. PROGRAMACION II','J.MAYTA','LAB 1');
 INSERT INTO CURSOS VALUES('73451138','4:00 4:45','LUNES','DESARROLLO E IMPLEMENTACION DE APLICACIONES WEB','R.MIRANDA','LAB 2');
 INSERT INTO CURSOS VALUES('73451138','4:45 5:30','LUNES','DESARROLLO E IMPLEMENTACION DE APLICACIONES WEB','R.MIRANDA','LAB 2');
 INSERT INTO CURSOS VALUES('73451138','2:00 2:45','MARTES','ANALI.DISE.SIST.AVAN','G.ESCOBEDO','LAB 1');
 INSERT INTO CURSOS VALUES('73451138','2:45 3:30','MARTES','ANALI.DISE.SIST.AVAN','G.ESCOBEDO','LAB 1');
 INSERT INTO CURSOS VALUES('73451138','4:00 4:45','MARTES','LEN. PROGRAMACION II','J.MAYTA','LAB 1');
 INSERT INTO CURSOS VALUES('73451138','4:45 5:30','MARTES','LEN. PROGRAMACION II','J.MAYTA','LAB 1');